export default {
    SET_CELL_VALUE: 'SET_CELL_VALUE',
    ON_SET_VALUE: 'ON_SET_VALUE', 
    SET_NOTE_VALUE: 'SET_NOTE_VALUE', 
    SET_CELL_SELECTED: 'SET_CELL_SELECTED',
    TOGGLE_INPUT_MODE: 'TOGGLE_INPUT_MODE', 
    CHECK_NEARBY_CELLS: 'CHECK_NEARBY_CELLS',
    START_GAME: 'START_GAME',
    NEW_GAME: 'NEW_GAME',
    ON_SOLVE: 'ON_SOLVE' 
}